### ISSUE TITLE
Bug: Chart test command should be able to override chart version

### ISSUE THREAD

**Issue by alexstojda** [silphid/testchart#2]
For charts that update their Chart.yaml, tests' expected files will need to be updated ever version change since helm injects annotations containing the appVersion and chart version. 

Ex: https://github.com/nestoca/joy-generator/actions/runs/5881501984/job/15950102359

`testchart` should have a way to override the chart version and appVersion so that the expected files do not need to be updated each release.

**Comment by silphid** [comment]
Thanks for proposing that feature request @alexstojda!

Flags `--chart-version` and `--app-version` have been added in release `v0.0.27`:
https://github.com/silphid/testchart/releases/tag/v0.0.27

Enjoy the `testchart` experience! 😁
